### ISSUE TITLE
Generator crashes

### ISSUE THREAD

**Issue by zazen00** [matheushf/generator-angularfire-express#7] opened 2017-01-12 15:56 UTC
After I installed the dependencies I ran the generator, I answered all the initial questions and as it's running it crashes with this error:

...
```
  create     app\views\main.html
   create     app\images\yeoman.png
module.js:327
    throw err;
    ^

Error: Cannot find module '../script-base2.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\zazen0\AppData\Roaming\npm\node_modules\generator-angularfire-express\main\index.js:6:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
...

Any help would be appreciated. I've tried attempting an npm install after the failure then running it; no go, the generator doesn't make it far enough.

**Comment by matheushf** [comment] 2017-01-13 03:20
Can you uninstall/install the generator and try again? I've just tested it here and it worked. If it fail tell me and I will check again. #2 [script-base ](https://github.com/matheushf/generator-angularfire-express/issues/2)

**Comment by zazen00** [comment] 2017-01-13 15:41
I uninstalled and re-installed; same problem. Could it be another dependancy not being updated? I've tried updating all my npm packages as well. My coworker gets the same error on his machine; we're both on windows 10.

**Comment by matheushf** [comment] 2017-01-15 18:28
The problem is the module "script-base" not being found due to the forward slashes used in windows I believe. I've made a change to use the module 'path' from Node.js, update your generator and try again please.

**Comment by matheushf** [comment] 2017-01-17 04:30
Tell me if it worked.

**Comment by serdaraglamis** [comment] 2017-01-22 19:07
Hi @matheushf I tried but its not working I changed my node versions (from 5.x.x to 7.4.0) then 6.x.x but nothing changed. I am using MacOS Sierra

**Comment by matheushf** [comment] 2017-01-24 23:13
I just tested in Windows, it's working now. I think it will work in MacOS as well.

Please update your generators and give me a feedback.

**Comment by Kluskey** [comment] 2017-02-02 23:34
Generator worked for me on macOS 10.12.3 @matheushf 

(As an aside though, I had to add `.config(['$locationProvider', function($locationProvider) { $locationProvider.hashPrefix(''); }])` to routes.js because ng-route wasn't working otherwise)

**Comment by matheushf** [comment] 2017-02-21 12:38
I will check that, thanks!

Closing issue since it's solved.

**Closed as completed by matheushf** 2017-02-21 12:38 UTC
Labels: bug
